<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="diffbot" params="prefix">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="0.3" /> <!-- arbitrary value for base mass -->
  <xacro:property name="base_width" value="0.1" />
  <xacro:property name="base_length" value="0.1" />
  <xacro:property name="base_height" value="0.05" />
  <xacro:property name="wheel_mass" value="0.3" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len" value="0.020" />
  <xacro:property name="wheel_radius" value="0.015" />
  <xacro:property name="caster_wheel_mass" value="0.1" /> <!-- arbitrary value for caster wheel mass -->
  <xacro:property name="caster_wheel_radius" value="0.015" />
  <xacro:property name="z_offset" value="-${base_height/2}" /> <!-- Space btw top of beam and the each joint -->


  <link name = "base_link">
        <visual>
            <geometry>
                <box size = "0.5 0.46 0.2" />
            </geometry>
            <origin xyz = "0 0 0.46" rpy = "0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size = "0.5 0.46 0.2" />
            </geometry>
            <origin xyz = "0 0 0.46" rpy = "0 0 0" />
        </collision>
    </link>

    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.025" />
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size = "0.1 0.1 0.025" />
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
        </collision>
    </link>

    <xacro:macro name="upper_link" params="prefix">
        <link name = "${prefix}_upper_link">
            <visual>
                <geometry>
                    <box size = "0.5 0.03 0.03" />
                </geometry>
                <origin xyz = "0 0 0" rpy = "0 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <box size = "0.5 0.03 0.03" />
                </geometry>
                <origin xyz = "0 0 0" rpy = "0 0 0" />
            </collision>
        </link>
    </xacro:macro>

    <xacro:upper_link prefix="left" />
    <xacro:upper_link prefix="right" />

    <xacro:macro name="vertical_link" params="prefix">
        <link name = "${prefix}_vertical_link">
            <visual>
                <geometry>
                    <box size = "0.03 0.03 0.2" />
                </geometry>
                <origin xyz = "0 0 -0.085" rpy = "0 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <box size = "0.03 0.03 0.2" />
                </geometry>
                <origin xyz = "0 0 -0.085" rpy = "0 0 0" />
            </collision>
        </link>
    </xacro:macro>

    <xacro:vertical_link prefix="left_front_1" />
    <xacro:vertical_link prefix="left_back_1" />
    <xacro:vertical_link prefix="right_front_1" />
    <xacro:vertical_link prefix="right_back_1" />

    <xacro:macro name="horizontal_link" params="prefix">
        <link name = "${prefix}_horizontal_link">
            <visual>
                <geometry>
                    <box size = "0.3 0.03 0.03" />
                </geometry>
                <origin xyz = "0 0 0" rpy = "0 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <box size = "0.3 0.03 0.03" />
                </geometry>
                <origin xyz = "0 0 0" rpy = "0 0 0" />
            </collision>
        </link>
    </xacro:macro>

    <xacro:horizontal_link prefix="left_front" />
    <xacro:horizontal_link prefix="left_back" />
    <xacro:horizontal_link prefix="right_front" />
    <xacro:horizontal_link prefix="right_back" />

    <xacro:macro name="vertical_bottom_link" params="prefix">
        <link name = "${prefix}_vertical_bottom_link">
            <visual>
                <geometry>
                    <box size = "0.03 0.03 0.2" />
                </geometry>
                <origin xyz = "0 0 -0.085" rpy = "0 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <box size = "0.03 0.03 0.2" />
                </geometry>
                <origin xyz = "0 0 -0.085" rpy = "0 0 0" />
            </collision>
        </link>
    </xacro:macro>

    <xacro:vertical_bottom_link prefix="left_front_f" />
    <xacro:vertical_bottom_link prefix="left_front_b" />
    <xacro:vertical_bottom_link prefix="left_back_f" />
    <xacro:vertical_bottom_link prefix="left_back_b" />

    <xacro:vertical_bottom_link prefix="right_front_f" />
    <xacro:vertical_bottom_link prefix="right_front_b" />
    <xacro:vertical_bottom_link prefix="right_back_f" />
    <xacro:vertical_bottom_link prefix="right_back_b" />

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="0.08" length="0.025" />
                </geometry>
            <origin xyz ="0 0.0125 0" rpy ="-1.57 0 0" />
            <material name="white" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.08" length="0.025" />
                </geometry>
            <origin xyz ="0 0.0125 0" rpy = "-1.57 0 0" />
            </collision>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="left_front_f" />
    <xacro:wheel_link prefix="left_front_b" />
    <xacro:wheel_link prefix="left_back_f" />
    <xacro:wheel_link prefix="left_back_b" />

    <xacro:wheel_link prefix="right_front_f" />
    <xacro:wheel_link prefix="right_front_b" />
    <xacro:wheel_link prefix="right_back_f" />
    <xacro:wheel_link prefix="right_back_b" />

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar" />
        <origin xyz="0 0 0.5725" rpy="0 0 0" /> 
    </joint>

    <joint name="base_left_joint" type="fixed">
        <parent link="base_link" />
        <child link="left_upper_link" />
        <origin xyz="0 0.245 0.46" rpy="0 0 0" /> 
    </joint>

    <joint name="base_right_joint" type="fixed">
        <parent link="base_link" />
        <child link="right_upper_link" />
        <origin xyz="0 -0.245 0.46" rpy="0 0 0" /> 
    </joint>

    <joint name="left_front_1_vertical_joint" type="fixed">
        <parent link="left_upper_link" />
        <child link="left_front_1_vertical_link" />
        <origin xyz="0.265 0 0" rpy="0 0 0" /> 
    </joint>

    <joint name="left_back_1_vertical_joint" type="fixed">
        <parent link="left_upper_link" />
        <child link="left_back_1_vertical_link" />
        <origin xyz="-0.265 0 0" rpy="0 0 0" /> 
    </joint>

    <joint name="right_front_1_vertical_joint" type="fixed">
        <parent link="right_upper_link" />
        <child link="right_front_1_vertical_link" />
        <origin xyz="0.265 0 0" rpy="0 0 0" /> 
    </joint>

    <joint name="right_back_1_vertical_joint" type="fixed">
        <parent link="right_upper_link" />
        <child link="right_back_1_vertical_link" />
        <origin xyz="-0.265 0 0" rpy="0 0 0" /> 
    </joint>

    <joint name="left_front_horizontal_joint" type="fixed">
        <parent link="left_front_1_vertical_link" />
        <child link="left_front_horizontal_link" />
        <origin xyz="0 0 -0.2" rpy="0 0 0" /> 
    </joint>

    <joint name="left_back_horizontal_joint" type="fixed">
        <parent link="left_back_1_vertical_link" />
        <child link="left_back_horizontal_link" />
        <origin xyz="0 0 -0.2" rpy="0 0 0" /> 
    </joint>

    <joint name="right_front_horizontal_joint" type="fixed">
        <parent link="right_front_1_vertical_link" />
        <child link="right_front_horizontal_link" />
        <origin xyz="0 0 -0.2" rpy="0 0 0" /> 
    </joint>

    <joint name="right_back_horizontal_joint" type="fixed">
        <parent link="right_back_1_vertical_link" />
        <child link="right_back_horizontal_link" />
        <origin xyz="0 0 -0.2" rpy="0 0 0" /> 
    </joint>

    <joint name="left_front_f_vertical_bottom_joint" type="fixed">
        <parent link="left_front_horizontal_link" />
        <child link="left_front_f_vertical_bottom_link" />
        <origin xyz="0.165 0 0" rpy="0 0 0" /> 
    </joint>

    <joint name="left_front_b_vertical_bottom_joint" type="fixed">
        <parent link="left_front_horizontal_link" />
        <child link="left_front_b_vertical_bottom_link" />
        <origin xyz="-0.165 0 0" rpy="0 0 0" /> 
    </joint>

    <joint name="left_back_f_vertical_bottom_joint" type="fixed">
        <parent link="left_back_horizontal_link" />
        <child link="left_back_f_vertical_bottom_link" />
        <origin xyz="0.165 0 0" rpy="0 0 0" /> 
    </joint>

    <joint name="left_back_b_vertical_bottom_joint" type="fixed">
        <parent link="left_back_horizontal_link" />
        <child link="left_back_b_vertical_bottom_link" />
        <origin xyz="-0.165 0 0" rpy="0 0 0" /> 
    </joint>

    <joint name="right_front_f_vertical_bottom_joint" type="fixed">
        <parent link="right_front_horizontal_link" />
        <child link="right_front_f_vertical_bottom_link" />
        <origin xyz="0.165 0 0" rpy="0 0 0" /> 
    </joint>

    <joint name="right_front_b_vertical_bottom_joint" type="fixed">
        <parent link="right_front_horizontal_link" />
        <child link="right_front_b_vertical_bottom_link" />
        <origin xyz="-0.165 0 0" rpy="0 0 0" /> 
    </joint>

    <joint name="right_back_f_vertical_bottom_joint" type="fixed">
        <parent link="right_back_horizontal_link" />
        <child link="right_back_f_vertical_bottom_link" />
        <origin xyz="0.165 0 0" rpy="0 0 0" /> 
    </joint>

    <joint name="right_back_b_vertical_bottom_joint" type="fixed">
        <parent link="right_back_horizontal_link" />
        <child link="right_back_b_vertical_bottom_link" />
        <origin xyz="-0.165 0 0" rpy="0 0 0" /> 
    </joint>

    <joint name="left_front_f_wheel_joint" type="continuous">
        <parent link="left_front_f_vertical_bottom_link" />
        <child link="left_front_f_wheel_link"/>
        <origin xyz="0 0.015 -0.17" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="left_front_b_wheel_joint" type="continuous">
        <parent link="left_front_b_vertical_bottom_link" />
        <child link="left_front_b_wheel_link"/>
        <origin xyz="0 0.015 -0.17" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

        <joint name="right_front_f_wheel_joint" type="continuous">
        <parent link="right_front_f_vertical_bottom_link" />
        <child link="right_front_f_wheel_link"/>
        <origin xyz="0 -0.04 -0.17" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="right_front_b_wheel_joint" type="continuous">
        <parent link="right_front_b_vertical_bottom_link" />
        <child link="right_front_b_wheel_link"/>
        <origin xyz="0 -0.04 -0.17" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="left_back_f_wheel_joint" type="continuous">
        <parent link="left_back_f_vertical_bottom_link" />
        <child link="left_back_f_wheel_link"/>
        <origin xyz="0 0.015 -0.17" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="left_back_b_wheel_joint" type="continuous">
        <parent link="left_back_b_vertical_bottom_link" />
        <child link="left_back_b_wheel_link"/>
        <origin xyz="0 0.015 -0.17" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

        <joint name="right_back_f_wheel_joint" type="continuous">
        <parent link="right_back_f_vertical_bottom_link" />
        <child link="right_back_f_wheel_link"/>
        <origin xyz="0 -0.04 -0.17" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="right_back_b_wheel_joint" type="continuous">
        <parent link="right_back_b_vertical_bottom_link" />
        <child link="right_back_b_wheel_link"/>
        <origin xyz="0 -0.04 -0.17" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>
  </xacro:macro>  

</robot>
  <!-- Base Link -->
  <!-- <link name="${prefix}base_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia
        ixx="${base_mass / 12.0 * (base_length*base_length + base_height*base_height)}" ixy="0.0" ixz="0.0"
        iyy="${base_mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
        izz="${base_mass / 12.0 * (base_width*base_width + base_length*base_length)}"/>
      </inertial>
    </link>

    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_wheel"/>
      <origin xyz="0 -${base_width/2} ${z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- left wheel Link -->
    <link name="${prefix}left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * wheel_radius*wheel_radius}" iyz="0.0"
          izz="${wheel_mass / 12.0 * wheel_radius*wheel_radius}"/>
        </inertial>
      </link>

    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_wheel"/>
      <origin xyz="0 ${base_width/2} ${z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- right wheel Link -->
    <link name="${prefix}right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * wheel_radius*wheel_radius}" iyz="0.0"
          izz="${wheel_mass / 12.0 * wheel_radius*wheel_radius}"/>
        </inertial>
      </link>

    <joint name="${prefix}caster_frontal_wheel_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}caster_frontal_wheel"/>
      <origin xyz="${base_width/2 - caster_wheel_radius} 0 ${z_offset}" rpy="0 0 0"/>
    </joint>

    <!-- caster frontal wheel Link -->
    <link name="${prefix}caster_frontal_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${caster_wheel_mass}"/>
        <inertia
          ixx="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" ixy="0.0" ixz="0.0"
          iyy="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" iyz="0.0"
          izz="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}"/>
        </inertial>
      </link>

    <joint name="${prefix}caster_rear_wheel_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}caster_rear_wheel"/>
      <origin xyz="${-base_width/2 + caster_wheel_radius} 0 ${z_offset}" rpy="0 0 0"/>
    </joint>

    <!-- caster rear wheel Link -->
    <link name="${prefix}caster_rear_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${caster_wheel_mass}"/>
        <inertia
          ixx="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" ixy="0.0" ixz="0.0"
          iyy="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" iyz="0.0"
          izz="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}"/>
        </inertial>
      </link>

  </xacro:macro>

</robot> -->
